### ISSUE TITLE
Reply to POST request with status code

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/USB-Nugget#25]
When posting a command to the Nugget via the web interface, there is no response. This causes a nasty crash with Requests when trying to script commands with Python.

It would be much better to respond to the POST request with a status code to indicate if the payload has been received and run or not.

**Comment by skickar** [comment]
For remote control scripts, it would be useful to send a response per command that is executed to update the interface page and any script running. 

That way, a script running would get feedback on what parts of their script ran in real time and could see if it got stuck or stopped.

**Comment by AlexLynd** [comment]
Latest PR solves this feature request.
