### ISSUE TITLE
MacOS Default Payload Not Valid

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/USB-Nugget#33]
The MacOS default payload does not work as intended. The GUI and command key are switched and the timing is big wrong.

The correct script is:

DELAY 1000
GUI SPACE
DELAY 1000
STRING terminal
DELAY 1000
ENTER
DELAY 1000
STRING open 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'
ENTER
DELAY 1000
GUI TAB
DELAY 1000
STRING osascript -e 'set volume 7' && killall Terminal
ENTER
DELAY 1500
STRING f

**Comment by AlexLynd** [comment]
Updated the default Mac OS payload in the latest v1.1 release. #53
