### ISSUE TITLE
Setting LED color doesn't work on main branch

### ISSUE THREAD

**Issue by brandonpaiz** [HakCat-Tech/USB-Nugget#34]
Running the default example script does not set LED color when built/flashed from main branch. When flashed from the latest release binary, it does work.

**Comment by skickar** [comment]
We might used this as an opportunity to update to setting LED color by RGB value instead of a key color in the future. Weird behavior that the compiled does not work but Alex's binary does.

**Comment by AlexLynd** [comment]
This issue is fixed.
