### ISSUE TITLE
1.04 upgrade brick recovery?

### ISSUE THREAD

**Issue by HeinrichII** [HakCat-Tech/USB-Nugget#50]
I have the 2.1 nugget board, which it seems has no ZERO button.  I was following the chrome update procedure on an MX Linux lapton.  It erased fine, And I used the esp web flasher, which has a banner that says it's not supported anymore.  I pressed on anyway, and it seemed to program fine...green bar all the way across, then when finished I noticed the bright green LED turned off, and following instructions, I unplugged it (instead of hitting the disconnect button). When I plugged it back in-nothing.  so then I hit the reset button...still nothing.  I reran the procedure using esp web flasher, even though the banner directed to go to esptool. same end result as above.   So then I tried the ESPtool, which is not only a terminal version, but they now have a web flash version also-so used that. Same end result.  Feels like I've bricked this little unit.  P.S. the blue led on the espy board blinks on connection and while hitting the reset button, so it's getting power, also when I plug it into either a windows box or linux, still just a dead little cat. ;(

_Originally posted by @HeinrichII in https://github.com/HakCat-Tech/USB-Nugget/issues/31#issuecomment-1207493636_

**Comment by AlexLynd** [comment]
Hey Heinrichll!
Does the ESP module on the back your Nugget look like the image below?
If it doesn't have a zero button, its likely that you have a WiFi Nugget instead of a USB Nugget.  This software won't be able to run on a WiFi Nugget. 

We apologize for the branding confusion, and we're trying to create a clearer dichotomy between the products we offer.  The WiFi Nugget can only run WiFi attack software, and the USB Nugget can only run USB attack software, due to physical hardware differences.

![image](https://user-images.githubusercontent.com/22926680/184802880-938958be-8499-4e1c-b88a-64a217f245f1.png)

**Comment by HeinrichII** [comment]
Hey Alex, sorry for the late response...the flatpack on the back is a metallic module,  seems to be bricked right now, any suggestions?
Thanks for the response!
    On Tuesday, August 16, 2022 at 12:18:18 AM CDT, Alex Lynd ***@***.***> wrote:  
 
 


Hey Heinrichll!
Does the ESP module on the back your Nugget look like the image below?
If it doesn't have a zero button, its likely that you have a WiFi Nugget instead of a USB Nugget. This software won't be able to run on a WiFi Nugget.

We apologize for the branding confusion, and we're trying to create a clearer dichotomy between the products we offer. The WiFi Nugget can only run WiFi attack software, and the USB Nugget can only run USB attack software, due to physical hardware differences.

**Comment by AlexLynd** [comment]
Hey Heinrich! I would recommend trying to flash some of our WiFi Nugget projects instead.  The [WiFi Deauther](https://github.com/HakCat-Tech/WiFi-Nugget/blob/main/NuggetDeauther.bin.bin) is our most popular supported attack tool, but we're also working on developing the [Nugget Invader](https://github.com/HakCat-Tech/Nugget-Invader/releases/tag/v1.0) as our flagship software.

**Comment by HeinrichII** [comment]
Alex, I'm really not trying to be a PITA, but this is the return when I try to follow your youtube instruction.


Google has no solution...still a lifeless cat.  It's about worth it to me to just buy a new one.  trying everthing to get this working...
Sorry to keep bugging you. Any help would be great.
v/r,Hein
    On Saturday, August 20, 2022 at 05:17:33 PM CDT, Alex Lynd ***@***.***> wrote:  
 
 


Hey Heinrich! I would recommend trying to flash some of our WiFi Nugget projects instead. The WiFi Deauther is our most popular supported attack tool, but we're also working on developing the Nugget Invader as our flagship software.
