### ISSUE TITLE
v1.1 release

### ISSUE THREAD

**Issue by gauntface** [HakCat-Tech/USB-Nugget#51]
Are there any plans to release a v1.1 release with a .bin?

I'm having some issues connect to the device on my laptop and hoping flashing the device will fix it.

Cheers,
Matt

**Comment by AlexLynd** [comment]
Hey! 
We had some issues generating the final binary file so pushed off the upload for a while.  
[You can find the latest release (v1.1) here!](https://github.com/HakCat-Tech/USB-Nugget/releases/tag/v1.1-beta)  Let us know if you have any other problems.
