### ISSUE TITLE
add how-to guide for flashing firmware with esptools

### ISSUE THREAD

**Issue by capsulecorplab** [HakCat-Tech/USB-Nugget#59]
a [how-to guide](https://documentation.divio.com/how-to-guides/) containing:

- [x] - steps for cloning or downloading & extracting from [release page](https://github.com/HakCat-Tech/USB-Nugget/releases)
- [x] - (link to) instructions for installing [esptools.py](https://docs.espressif.com/projects/esptool/en/latest/esp32/)
- [x] - steps for flashing firmware onto nugget

**Comment by AlexLynd** [comment]
Done!  We just pushed that documentation yesterday here - https://usbnugget.com/docs/guides/update-with-esptool/

We're working on making the documentation more coherent, but if you have any suggestions / requests, you can leave them [on our repo](https://github.com/HakCat-Tech/usbnugget.com).
