### ISSUE TITLE
MacOS keyboard profiler prevents payload deployment

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/USB-Nugget#6]
Set the MAC address to an Apple device and this won't happen, no other issues created by doing this

**Comment by abdallaaaaaaa** [comment]
ok maybe

**Comment by AlexLynd** [comment]
This issue is solved in our latest release!   Just create the file `usbnugget.conf` on your NUGGET drive, and add the following parameters.  By default, I've made this an apple keyboard, so there shouldn't be any issues.
```
vid:0x05ac
pid:0x20b
```
https://github.com/HakCat-Tech/USB-Nugget/releases/tag/v1.1-beta
