### ISSUE TITLE
Prominent image in README shows incorrect URL

### ISSUE THREAD

**Issue by brandonpaiz** [HakCat-Tech/USB-Nugget#76]
The [RubberNugget-Features.png](https://github.com/HakCat-Tech/USB-Nugget/blob/main/images/RubberNugget-Features.png) image shows the URL "wifinugget.com" nugget. This is misleading as the project is called USBNugget, and is an entirely different product than the Wi-Fi Nugget

If fixing this issue, consider resolving https://github.com/HakCat-Tech/USB-Nugget/issues/77 at the same time as it's closely related.

**Comment by AlexLynd** [comment]
Resolved with [USB-Nugget.png](https://github.com/HakCat-Tech/USB-Nugget/blob/main/images/USB-Nugget.png)!
