### ISSUE TITLE
Prominent image in README shows incorrect version

### ISSUE THREAD

**Issue by brandonpaiz** [HakCat-Tech/USB-Nugget#77]
The [RubberNugget-Features.png](https://github.com/HakCat-Tech/USB-Nugget/blob/main/images/RubberNugget-Features.png) image shows the version as 1.0 which is incorrect. The version should probably be removed altogether, so we don't have to change it for every release.

Or, we could generate the text on this image using a script -- the imagemagick library comes to mind. But this approach also seems like an unnecessary waste of time.

If fixing this issue, consider resolving https://github.com/HakCat-Tech/USB-Nugget/issues/76 at the same time as it's closely related.

**Comment by AlexLynd** [comment]
Issue is fixed! I updated the image.
