### ISSUE TITLE
Feature: add scroll if 3+ folders/payloads

### ISSUE THREAD

**Issue by skickar** [HakCat-Tech/USB-Nugget#9]
Currently, if the user adds more than 3 folders or payloads, only 3 will ever be visible.

I propose we add logic that maintains the quick-launch layout, but adds a switch for 3+ items that turns the down button into a "page down" scroll.

When loading a folder with more than 3 items, the first 3 items should be mapped to the up, right, and left buttons. The down button goes to the next page, continuing until the last page of 3 items is reached. When the last page is reached, the down button becomes the "back" button as is standard now. 

![untitled@2x(2)](https://user-images.githubusercontent.com/40251293/165698992-31e7bc1e-2e48-40d4-8b73-db22293c611e.png)

**Comment by AlexLynd** [comment]
Closed in latest PR.  We've opted for a scrolling interface that works more intuitively.
